// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwxepwsfcxfifiupmjmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3eGVwd3NmY3hmaWZpdXBtam1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzEyMzYsImV4cCI6MjA2MDIwNzIzNn0.JkFaBiKJrrT2EYjJrcL-tYVR-SGYgDmm4yHs2z8K2Ag";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);